# Generated by Django 5.0 on 2024-03-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='percent',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='sender',
            name='status',
            field=models.CharField(choices=[('Sending_Shipment', 'Sending_Shipment'), ('On_the_move', 'On_the_move'), ('On_site', 'On_site'), ('Received', 'Received')], default='Sending_Shipment', max_length=20),
        ),
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Sending_Shipment', 'Sending_Shipment'), ('On_the_move', 'On_the_move'), ('On_site', 'On_site'), ('Received', 'Received')], default='Sending_Shipment', max_length=20)),
                ('percent', models.CharField(default=0, max_length=3)),
                ('message', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recieving a shipments',
            },
        ),
    ]
