# Generated by Django 4.2.6 on 2024-03-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_sender_percent_alter_sender_status_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciever',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='cargo.sender'),
        ),
    ]
