# Generated by Django 4.2.6 on 2024-03-21 16:55

import cargo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_reciever_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciever',
            name='id',
        ),
        migrations.AddField(
            model_name='reciever',
            name='custom_id',
            field=models.CharField(default=cargo.models.generate_custom_id, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
